# Generated by Django 3.2.9 on 2023-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_rename_name_paper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper',
            field=models.FileField(upload_to='paper/'),
        ),
    ]
