# Generated by Django 3.2.9 on 2023-04-08 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
